### ISSUE TITLE
Compatibility with IntelliJ IDEA 13

### ISSUE THREAD

**Issue by rpirsc13** [protostuff/protobuf-jetbrains-plugin#24]
Running Intellij Ultimate Idea 14.1.5 and i get this incompatibility error:

```
Plugin 'Protobuf Support' is incompatible with this installation
```

 I would really like to use this awesome plugin. Is it not compatible with Intellij 14 ?

**Comment by kshchepanovskyi** [comment]
Plugin is compatible with IntelliJ IDEA 2016.1 and higher versions. Originally I did not plan to support older versions.

There are two reasons why I decided to support this version and higher:

1. Starting from IDEA 2016.1 I could use Java 8 for development.
2. This is the version that I was using when I started this project.

As plugin gets more and more popular, I think it definitely makes sense to support older IDEA versions too.

It should not be hard to rewrite all code using Java 6 (or 7 - need to check what JDK is bundled with IDEA).
Following modules should be rewritten using Java 6 in order to make plugin for IDEA 14:

* this project
* https://github.com/protostuff/protostuff-compiler
* https://github.com/kshchepanovskyi/jetbrains/tree/gradle-integration (maybe)

**Comment by kshchepanovskyi** [comment]
If somebody is willing to help, I will gladly accept pull requests :)

**Comment by rpirsc13** [comment]
I will give it a shot. Will make a pull request after work.

**Comment by kshchepanovskyi** [comment]
Ok, let's do it.
I just checked IDEA 14 release notes, code should be rewritten using Java 6 language.

You can start from plugin code.
In order to simplify things, I will extract generated lexer and parser code from https://github.com/protostuff/protostuff-compiler to separate project, so that we do not need to move whole `protostuff-compiler` to Java 6 (streams are used heavily there).

**Comment by kshchepanovskyi** [comment]
It does make sense to rewrite `protostuff-compiler` dependency using Java 6 as well (as I have maven plugin there - there is no guarantee that all users have Java 8). I hope I will finish it in a couple of days.

**Comment by kshchepanovskyi** [comment]
@rpirsc13 I've just made all changes needed for IDEA 14 support, please checkout branch [13x](https://github.com/protostuff/protobuf-jetbrains-plugin/tree/13x), build it and try it out :)

**Comment by kshchepanovskyi** [comment]
Please report all problems that you find here.
I hope we will finish testing on this week, so I will make a public release after that.

**Comment by kshchepanovskyi** [comment]
Released in https://github.com/protostuff/protobuf-jetbrains-plugin/releases/tag/v0.6.0

**Comment by kshchepanovskyi** [comment]
Download statistics shows that there are not so many users who use old IDEA versions:

13 ... 15:
![image](https://cloud.githubusercontent.com/assets/4040120/18809600/b8dc11c0-8288-11e6-9082-6d482ff7ccd5.png)

2016.1+:
![image](https://cloud.githubusercontent.com/assets/4040120/18809595/a3516ae4-8288-11e6-82f3-4597918f28e6.png)

I decided to cancel my original plan to support IDEA 13 in the new releases.
