### ISSUE TITLE
import doesn't work?

### ISSUE THREAD

**Issue by zhYou** [protostuff/protobuf-jetbrains-plugin#65]
after upgrading, import syntax doesn't work. current version 0.10.0, previous version unknown.

**Comment by elvizlai** [comment]
previous works well, but now not

**Comment by kshchepanovskyi** [comment]
Hello. 

There are not changes related to resolving imports.
Only one feature has been added in v0.10.0 - "highlight unresolved references".
If some imports are highlighted as "unresolvable", it means they were not working before as well.

In order to fix it, you should tell to plugin where is the "sources root".

There are two ways of doing that:

1. You can mark directory as a source/resources root (right click on folder in project structure, "Mark forlder as...."):

![image](https://user-images.githubusercontent.com/4040120/28202383-c96d6f08-687d-11e7-905d-53dfcf6e0799.png)

2. You can configure directory as source/resources folder in maven/gradle/etc (if IDEA has support for that build system). See this pull request: https://github.com/protostuff/protobuf-jetbrains-plugin/pull/64/files

3. You can go to plugin settings, and and sources root there:

![image](https://user-images.githubusercontent.com/4040120/28202438-0fbe29ca-687e-11e7-964a-bb1f10dfcd4f.png)

**Comment by lodgvideon** [comment]
This workaround works. But I think many people store they *.proto files in resources folders.
Same issue.

**Comment by kshchepanovskyi** [comment]
Ok, let's think how it can be improved.

1. I can make error highlighting configurable (so that it will be like in previous version).
2. Plugin can try to resolve imports against current file location. If there is package statement, it can do lookup from parent folder.

I think secons option should solve problem for most of the people.

Any other ideas?

**Comment by kshchepanovskyi** [comment]
@zhYou @elvizlai @lodgvideon 
Check #66: Resolve imports relative to file's location
It will go to release `0.10.1` tomorrow.

Please write down a comment here if issue will be (or will not be) resolved after upgrade.

**Comment by kshchepanovskyi** [comment]
Released https://plugins.jetbrains.com/plugin/8277-protobuf-support/update/36949

**Comment by elvizlai** [comment]
thx, v0.10.1 works for me
