### ISSUE TITLE
[feature request] Field option 'json_name' support

### ISSUE THREAD

**Issue by Anricx** [protostuff/protobuf-jetbrains-plugin#90]
Version: 0.10.2
still not support field option 'json_name', editor will say 'Unresolved reference'.

````proto
syntax="proto3";

message Foo {
    int32 foo = 1 [json_name="bar_2d"];
}
````

https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#field

Is there any plan ?

**Comment by kshchepanovskyi** [comment]
Thanks for reporting this, I'll update `google/protobuf/descriptor.proto' bundled with plugin to the newest version.

Meanwhile, you can add new version of this file to your project, or add custom include path in plugin settings (make sure to point to correct path, so that this file can be resolved relatively against include path).

https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L211

**Comment by Mailerm** [comment]
thx, waiting for you next release!

**Comment by kshchepanovskyi** [comment]
While it is not published yet, you may try https://jenkins.ksprojects.org/job/protostuff/job/protobuf-jetbrains-plugin/job/master/6/artifact/build/distributions/protobuf-jetbrains-plugin-0.10.2.zip - I would appreciate any feedback.
